kind: Deployment
apiVersion: apps/v1
metadata:
  name: mm-controller-arduino
  namespace: mm-controller-arduino
  labels:
    app: mm-controller-arduino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm-controller-arduino
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mm-controller-arduino
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      serviceAccountName: mm-controller-arduino
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mm-controller-arduino
          env:        
            - name: WS_PORT
              valueFrom:
                configMapKeyRef:
                  name: mm-controller-arduino
                  key: WS_PORT
            - name: CONNECTOR_SVC
              valueFrom:
                configMapKeyRef:
                  name: mm-controller-arduino
                  key: CONNECTOR_SVC
          securityContext: 
            privileged: true
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/rciots/mm-controller-arduino:latest
          volumeMounts:
            - name: hostpath-dev
              mountPath: /dev
      volumes:
        - name: hostpath-dev
          hostPath:
              path: /dev
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600